version: '3.9'

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

services:
  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: agent-prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - agent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Grafana for metrics visualization
  grafana:
    image: grafana/grafana:latest
    container_name: agent-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - agent-network
    depends_on:
      - prometheus
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Override services to expose metrics endpoints
  api:
    environment:
      - PYTHONPATH=/app
      - DEPLOYMENT_PROFILE=${DEPLOYMENT_PROFILE:-lightweight}
      - ASR_SERVICE_URL=http://asr:8001
      - LLM_SERVICE_URL=http://llm:8002
      - TTS_SERVICE_URL=http://tts:8003
      - SARDAUKAR_TRANSLATOR_URL=http://sardaukar-translator:8004
      - SARDAUKAR_ENABLED=false
      - METRICS_ENABLED=true
      - PROMETHEUS_MULTIPROC_DIR=/tmp

  asr:
    environment:
      - PYTHONPATH=/app
      - WHISPER_MODEL=base
      - METRICS_ENABLED=true
      - PROMETHEUS_MULTIPROC_DIR=/tmp

  llm:
    environment:
      - PYTHONPATH=/app
      - MODEL_NAME=llama3
      - MODEL_PATH=/app/models
      - METRICS_ENABLED=true
      - PROMETHEUS_MULTIPROC_DIR=/tmp

  tts:
    environment:
      - PYTHONPATH=/app
      - PIPER_MODEL=en_US-lessac-medium
      - SARDAUKAR_TRANSLATOR_URL=http://sardaukar-translator:8004
      - METRICS_ENABLED=true
      - PROMETHEUS_MULTIPROC_DIR=/tmp