version: '3.9'
services:
  api:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./api:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
  # Additional service stubs can be added here
