global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Agent CAG API Service
  - job_name: 'agent-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # ASR Service
  - job_name: 'agent-asr'
    static_configs:
      - targets: ['asr:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # LLM Service
  - job_name: 'agent-llm'
    static_configs:
      - targets: ['llm:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # TTS Service
  - job_name: 'agent-tts'
    static_configs:
      - targets: ['tts:8083']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Sardaukar Translator Service
  - job_name: 'sardaukar-translator'
    static_configs:
      - targets: ['sardaukar-translator:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s

  # ChromaDB (when using full profile)
  - job_name: 'chroma'
    static_configs:
      - targets: ['chroma:8000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 30s

  # Neo4j (when using full profile)
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']
    metrics_path: '/metrics'
    scrape_interval: 30s