global:
  scrape_interval: ${METRICS_SCRAPE_INTERVAL:-15s}
  evaluation_interval: ${METRICS_SCRAPE_INTERVAL:-15s}

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:${PROMETHEUS_PORT:-9090}']

  # Agent CAG API Service
  - job_name: 'agent-api'
    static_configs:
      - targets: ['api:${API_PORT:-8000}']
    metrics_path: '/metrics'
    scrape_interval: ${SERVICE_SCRAPE_INTERVAL:-10s}

  # ASR Service
  - job_name: 'agent-asr'
    static_configs:
      - targets: ['asr:${ASR_PORT:-8001}']
    metrics_path: '/metrics'
    scrape_interval: ${SERVICE_SCRAPE_INTERVAL:-10s}

  # LLM Service
  - job_name: 'agent-llm'
    static_configs:
      - targets: ['llm:${LLM_PORT:-8002}']
    metrics_path: '/metrics'
    scrape_interval: ${SERVICE_SCRAPE_INTERVAL:-10s}

  # TTS Service
  - job_name: 'agent-tts'
    static_configs:
      - targets: ['tts:${TTS_PORT:-8003}']
    metrics_path: '/metrics'
    scrape_interval: ${SERVICE_SCRAPE_INTERVAL:-10s}

  # Sardaukar Translator Service
  - job_name: 'sardaukar-translator'
    static_configs:
      - targets: ['sardaukar-translator:${SARDAUKAR_PORT:-8000}']
    metrics_path: '/api/metrics'
    scrape_interval: ${SERVICE_SCRAPE_INTERVAL:-10s}

  # ChromaDB (when using full profile)
  - job_name: 'chroma'
    static_configs:
      - targets: ['chroma:${CHROMA_PORT:-8000}']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 30s

  # Neo4j (when using full profile)
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']
    metrics_path: '/metrics'
    scrape_interval: 30s